server:
  port: 8762
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/